import { test, expect } from '@playwright/test'
import { launchApp, waitForReady, type LaunchedApp } from './_helpers'
import { createServer } from 'node:http'

// Does the whole chain work: add a feed -> fetch -> parse -> store -> read back?
// Served from a local HTTP server so the test does not depend on Google being
// up, but the path exercised is the real one (net.fetch, real parser, real db).
test('subscribing to an ICS feed mirrors its events', async () => {
  const ics = [
    'BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//Test//EN', 'X-WR-CALNAME:Team',
    'BEGIN:VEVENT', 'UID:one@test', 'DTSTART:20260916T090000Z', 'DTEND:20260916T100000Z',
    'SUMMARY:Pipeline review', 'LOCATION:Zoom', 'END:VEVENT',
    'BEGIN:VEVENT', 'UID:rep@test', 'DTSTART:20260917T230000Z', 'DTEND:20260917T233000Z',
    'RRULE:FREQ=WEEKLY;BYDAY=TH;COUNT=4', 'SUMMARY:Standup', 'END:VEVENT',
    'END:VCALENDAR'
  ].join('\r\n')

  const server = createServer((_req, res) => {
    res.writeHead(200, { 'Content-Type': 'text/calendar' })
    res.end(ics)
  })
  await new Promise<void>((r) => server.listen(0, '127.0.0.1', r))
  const port = (server.address() as { port: number }).port
  const feed = `http://127.0.0.1:${port}/cal.ics`

  const launched: LaunchedApp = await launchApp()
  const { window } = launched
  await waitForReady(window)

  const result = await window.evaluate(async (url) => {
    const api = (window as unknown as { api: Record<string, any> }).api
    const added = await api.externalCalendars.add({
      provider: 'ics', name: 'Team', sourceRef: url
    })
    const cals = await api.externalCalendars.list()
    const events = await api.externalCalendars.listEvents(
      Date.UTC(2026, 8, 1), Date.UTC(2026, 10, 1)
    )
    return {
      added,
      calCount: cals.length,
      lastError: cals[0]?.lastSyncError ?? null,
      lastSyncAt: cals[0]?.lastSyncAt ?? null,
      titles: events.map((e: { title: string }) => e.title),
      count: events.length,
      firstStart: events[0] ? new Date(events[0].startMs).toISOString() : null
    }
  }, feed)

  server.close()

  expect(result.added.ok).toBe(true)
  expect(result.lastError).toBeNull()
  expect(result.lastSyncAt).toBeTruthy()
  // One single event plus four generated by the weekly rule.
  expect(result.count).toBe(5)
  expect(result.titles.filter((t: string) => t === 'Standup')).toHaveLength(4)
  expect(result.firstStart).toBe('2026-09-16T09:00:00.000Z')

  await launched.dispose()
})
