// Local snapshot of the capability defaults — used when there's no
// signed-in account (so we can't hit /account/capabilities) or while
// the first server fetch hasn't returned yet.
//
// Sync rule: when haptyx-shared/src/capabilities.ts updates, refresh
// this snapshot AND the parallel snapshot in
// projects/focusbuddy-signal/src/capabilities.ts. There's a drift test
// — keep the three in sync.

export type TierId = 'free' | 'pro' | 'team'
export type CapabilityValue = boolean | number | string

export const CAPABILITY_DEFAULTS: Record<string, Record<TierId, CapabilityValue>> = {
  product_desk: { free: true, pro: true, team: true },
  product_office: { free: true, pro: true, team: true },
  product_brain: { free: true, pro: true, team: true },
  product_people: { free: true, pro: true, team: true },
  office_docs: { free: true, pro: true, team: true },
  office_sheets: { free: true, pro: true, team: true },
  office_slides: { free: true, pro: true, team: true },
  office_draw: { free: true, pro: true, team: true },
  office_design: { free: true, pro: true, team: true },
  workspace_canvas: { free: true, pro: true, team: true },
  multiple_desks: { free: 'Unlimited', pro: 'Unlimited', team: 'Unlimited' },
  desk_themes: { free: true, pro: true, team: true },
  edge_pan: { free: true, pro: true, team: true },
  widget_drag_drop: { free: true, pro: true, team: true },
  widget_resize_rotate: { free: true, pro: true, team: true },
  widget_sticky: { free: true, pro: true, team: true },
  widget_task_list: { free: true, pro: true, team: true },
  widget_files: { free: true, pro: true, team: true },
  widget_browser: { free: true, pro: true, team: true },
  widget_notes: { free: true, pro: true, team: true },
  widget_table: { free: true, pro: true, team: true },
  widget_timer: { free: true, pro: true, team: true },
  widget_calendar: { free: true, pro: true, team: true },
  task_creation: { free: true, pro: true, team: true },
  critical_step_highlight: { free: true, pro: true, team: true },
  ai_task_setup: { free: true, pro: true, team: true },
  five_minute_lockin: { free: true, pro: true, team: true },
  extended_lockin: { free: true, pro: true, team: true },
  drift_detection: { free: true, pro: true, team: true },
  defer_to_later: { free: true, pro: true, team: true },
  resume_summary: { free: true, pro: true, team: true },
  task_templates: { free: true, pro: true, team: true },
  team_task_assignment: { free: false, pro: false, team: true },
  speeddeck_universal: { free: true, pro: true, team: true },
  speeddeck_per_task: { free: true, pro: true, team: true },
  speeddeck_keystrokes: { free: true, pro: true, team: true },
  speeddeck_app_launch: { free: true, pro: true, team: true },
  speeddeck_url_open: { free: true, pro: true, team: true },
  speeddeck_multi_step: { free: true, pro: true, team: true },
  speeddeck_ai_gen: { free: true, pro: true, team: true },
  speeddeck_conflict: { free: true, pro: true, team: true },
  speeddeck_chords: { free: true, pro: true, team: true },
  ai_chat: { free: true, pro: true, team: true },
  byo_anthropic_key: { free: true, pro: true, team: true },
  ai_no_proxy: { free: true, pro: true, team: true },
  ai_task_breakdown: { free: true, pro: true, team: true },
  ai_session_summary: { free: true, pro: true, team: true },
  body_double: { free: false, pro: true, team: true },
  ai_drift_prompts: { free: true, pro: true, team: true },
  share_link_send: { free: true, pro: true, team: true },
  universal_share: { free: true, pro: true, team: true },
  per_account_share: { free: true, pro: true, team: true },
  cloud_inbox: { free: true, pro: true, team: true },
  viewer_public_link: { free: true, pro: true, team: true },
  team_shared_decks: { free: false, pro: false, team: true },
  local_first_storage: { free: true, pro: true, team: true },
  multi_device_sync: { free: 3, pro: 'Unlimited', team: 'Unlimited' },
  export_workspace: { free: true, pro: true, team: true },
  import_workspace: { free: true, pro: true, team: true },
  workspace_history: { free: false, pro: true, team: true },
  master_password: { free: true, pro: true, team: true },
  no_telemetry: { free: true, pro: true, team: true },
  byo_key_only: { free: true, pro: true, team: true },
  two_factor: { free: true, pro: true, team: true },
  sso: { free: false, pro: false, team: true },
  session_audit: { free: false, pro: false, team: false },
  marketplace_browse: { free: true, pro: true, team: true },
  marketplace_install_free: { free: true, pro: true, team: true },
  marketplace_purchase: { free: true, pro: true, team: true },
  marketplace_credits: { free: false, pro: '$5/mo', team: '$10/seat/mo' },
  marketplace_publish: { free: false, pro: true, team: true },
  per_seat_billing: { free: false, pro: false, team: true },
  centralized_admin: { free: false, pro: false, team: true },
  usage_analytics: { free: false, pro: false, team: true },
  capability_matrix_edit: { free: false, pro: false, team: true },
  audit_log: { free: false, pro: false, team: false },
  priority_support: { free: false, pro: false, team: true },
  scim_provisioning: { free: false, pro: false, team: true },
  data_residency: { free: false, pro: false, team: false },
  self_hosting: { free: false, pro: false, team: false },

  // ── 2.4.x — voice, imports, mind-map, focus-mode & linking widgets ──────
  // (kept in sync with haptyx-shared + signal-server via `check:drift`)
  widget_mindmap: { free: true, pro: true, team: true },
  widget_voice_recorder: { free: true, pro: true, team: true },
  widget_diagram: { free: true, pro: true, team: true },
  widget_scratchpad: { free: true, pro: true, team: true },
  widget_focus_mode: { free: true, pro: true, team: true },
  widget_linking: { free: true, pro: true, team: true },
  widget_auto_arrange: { free: true, pro: true, team: true },
  voice_command: { free: true, pro: true, team: true },
  voice_command_streaming: { free: true, pro: true, team: true },
  voice_command_silence: { free: true, pro: true, team: true },
  voiceback: { free: true, pro: true, team: true },
  whisper_cloud: { free: true, pro: true, team: true },
  whisper_local: { free: true, pro: true, team: true },
  live_captions: { free: true, pro: true, team: true },
  mindmap_agents: { free: true, pro: true, team: true },
  file_import_text: { free: true, pro: true, team: true },
  file_import_csv: { free: true, pro: true, team: true },
  file_import_json: { free: true, pro: true, team: true },
  file_import_docx: { free: true, pro: true, team: true },

  // ── Cross-product functionality (Brain, Team, Comms, Calendar, Collab, Files) ──
  // Defaulted all-true so nobody loses access; tiering is the operator's call.
  office_interop_import: { free: true, pro: true, team: true },
  office_interop_export: { free: true, pro: true, team: true },
  office_ai_generate: { free: true, pro: true, team: true },
  office_present: { free: true, pro: true, team: true },
  office_comments: { free: true, pro: true, team: true },
  brain_workspace_ask: { free: true, pro: true, team: true },
  brain_create_actions: { free: true, pro: true, team: true },
  brain_daily_brief: { free: true, pro: true, team: true },
  brain_streaming: { free: true, pro: true, team: true },
  brain_scope: { free: true, pro: true, team: true },
  ai_trace: { free: true, pro: true, team: true },
  ai_apply_all: { free: true, pro: true, team: true },
  ai_web_search: { free: false, pro: true, team: true },
  ai_memory: { free: false, pro: true, team: true },
  ai_agent_loop: { free: false, pro: true, team: true },
  ai_usage_metering: { free: true, pro: true, team: true },
  people_map: { free: false, pro: false, team: true },
  presence: { free: false, pro: false, team: true },
  org_directory: { free: false, pro: false, team: true },
  multi_org: { free: false, pro: false, team: true },
  chat: { free: true, pro: true, team: true },
  meet: { free: true, pro: true, team: true },
  meet_schedule: { free: true, pro: true, team: true },
  calls: { free: true, pro: true, team: true },
  video_messages: { free: true, pro: true, team: true },
  knock: { free: true, pro: true, team: true },
  mail: { free: true, pro: true, team: true },
  mail_ai_replies: { free: false, pro: true, team: true },
  esign: { free: false, pro: true, team: true },
  time_blocking: { free: true, pro: true, team: true },
  meeting_ics: { free: true, pro: true, team: true },
  live_collaboration: { free: true, pro: true, team: true },
  realtime_coediting: { free: true, pro: true, team: true },
  file_manager: { free: true, pro: true, team: true },
  file_auto_tagging: { free: true, pro: true, team: true },
  password_vault: { free: true, pro: true, team: true },
  vault_backup: { free: false, pro: true, team: true },
  // 4.3.0 — browsing, the open tray, and the gaps from 4.2.x
  office_browser: { free: true, pro: true, team: true },
  ai_browse_drive: { free: false, pro: true, team: true },
  ai_browse_tasks: { free: false, pro: true, team: true },
  ai_browse_steer: { free: false, pro: true, team: true },
  ai_browse_findings: { free: false, pro: true, team: true },
  ai_browse_consent: { free: true, pro: true, team: true },
  open_tray: { free: true, pro: true, team: true },
  doc_to_desk: { free: true, pro: true, team: true },
  widget_custom_ai: { free: false, pro: true, team: true },
  mail_folders: { free: true, pro: true, team: true },
  mail_paging: { free: true, pro: true, team: true },
  mail_triage: { free: false, pro: true, team: true },
  attention_queue: { free: true, pro: true, team: true },
  attention_capture: { free: true, pro: true, team: true },
  day_planning: { free: false, pro: true, team: true },

}

/** Resolve a capability value for a tier from the local defaults snapshot. */
export function localResolve(tier: TierId, key: string): CapabilityValue {
  const row = CAPABILITY_DEFAULTS[key]
  return row?.[tier] ?? false
}
