import type { ArgSpec } from './contracts'

// DERIVED from the handler signatures in src/main/ipc — do not hand-edit.
//
// Regenerate with:  node scripts/derive-ipc-contracts.cjs --write
//
// tests/unit/ipcContracts.test.ts re-derives from source on every run and fails
// if this file and the handlers have drifted apart, so a signature change cannot
// leave a stale contract behind. That guard is the reason this can be a
// generated file at all rather than a second hand-kept copy of 257 argument
// lists — which is exactly the trap the work-item column manifest documents.
//
// Only channels with at least one enforceable, non-optional argument appear
// here. Everything else is deliberately unconstrained; see contracts.ts.

export const IPC_ARG_CONTRACTS: Record<string, readonly ArgSpec[]> = {
  'account:saveSession': [{ kind: 'object', optional: false, nullable: true }],
  'account:setCachedEmail': [{ kind: 'string', optional: false, nullable: true }],
  'account:setSkipped': [{ kind: 'boolean', optional: false, nullable: false }],
  'activity:logPress': [{ kind: 'object', optional: false, nullable: false }],
  'activity:setEnabled': [{ kind: 'boolean', optional: false, nullable: false }],
  'agent:verify': [{ kind: 'object', optional: false, nullable: false }],
  'agentBrowser:createRun': [{ kind: 'number', optional: false, nullable: false }],
  'agentBrowser:endRun': [{ kind: 'string', optional: false, nullable: false }],
  'agentBrowser:perform': [{ kind: 'string', optional: false, nullable: false }, { kind: 'any', optional: false, nullable: false }],
  'agentBrowser:stopRun': [{ kind: 'string', optional: false, nullable: false }],
  'agents:designProfile': [{ kind: 'string', optional: false, nullable: false }],
  'agents:listInvocationsForNode': [{ kind: 'string', optional: false, nullable: false }],
  'agents:previewInput': [{ kind: 'string', optional: false, nullable: false }],
  'agents:revealInFinder': [{ kind: 'string', optional: false, nullable: false }],
  'agents:run': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: true, nullable: false }, { kind: 'any', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: false }, { kind: 'number', optional: true, nullable: false }],
  'agents:setWorkspaceOverride': [{ kind: 'string', optional: false, nullable: false }],
  'agents:statsForSlug': [{ kind: 'string', optional: false, nullable: false }],
  'ai:enhanceRecord': [{ kind: 'object', optional: false, nullable: false }],
  'ai:extractActionsFromTranscript': [{ kind: 'object', optional: false, nullable: false }],
  'ai:extractCommitments': [{ kind: 'object', optional: false, nullable: false }],
  'ai:processTranscript': [{ kind: 'object', optional: false, nullable: false }],
  'ai:rewriteSelection': [{ kind: 'object', optional: false, nullable: false }],
  'ai:routeCommand': [{ kind: 'object', optional: false, nullable: false }],
  'ai:setMode': [{ kind: 'string', optional: false, nullable: false }],
  'ai:suggestDocContent': [{ kind: 'object', optional: false, nullable: false }],
  'ai:suggestPageContent': [{ kind: 'string', optional: false, nullable: false }],
  'ai:suggestTableRows': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'number', optional: false, nullable: false }],
  'ai:topUpCredits': [{ kind: 'number', optional: false, nullable: false }],
  'aiChat:appendMessage': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: true, nullable: false }, { kind: 'any', optional: true, nullable: true }],
  'aiChat:deleteConversation': [{ kind: 'string', optional: false, nullable: false }],
  'aiChat:getConversation': [{ kind: 'string', optional: false, nullable: false }],
  'aiChat:linkDesk': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'boolean', optional: true, nullable: false }],
  'aiChat:renameConversation': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }],
  'aiChat:setConversationMode': [{ kind: 'string', optional: false, nullable: false }, { kind: 'any', optional: false, nullable: false }],
  'aiChat:setConversationWebSearch': [{ kind: 'string', optional: false, nullable: false }, { kind: 'boolean', optional: false, nullable: false }],
  'aiChat:setMessageApplied': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }, { kind: 'any', optional: false, nullable: false }],
  'api:createToken': [{ kind: 'string', optional: false, nullable: false }, { kind: 'any', optional: false, nullable: false }],
  'api:revokeToken': [{ kind: 'string', optional: false, nullable: false }],
  'api:setEnabled': [{ kind: 'boolean', optional: false, nullable: false }],
  'api:setPort': [{ kind: 'number', optional: false, nullable: false }],
  'app:setBackgroundColor': [{ kind: 'string', optional: false, nullable: false }],
  'app:setZoomFactor': [{ kind: 'number', optional: false, nullable: false }],
  'apps:create': [{ kind: 'object', optional: false, nullable: false }],
  'apps:delete': [{ kind: 'string', optional: false, nullable: false }],
  'apps:get': [{ kind: 'string', optional: false, nullable: false }],
  'apps:update': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }],
  'bodyDouble:tick': [{ kind: 'string', optional: false, nullable: true }, { kind: 'any', optional: false, nullable: false }],
  'brand:set': [{ kind: 'object', optional: false, nullable: false }],
  'browserAgent:consent': [{ kind: 'string', optional: false, nullable: false }, { kind: 'boolean', optional: false, nullable: false }, { kind: 'boolean', optional: false, nullable: false }],
  'browserAgent:stop': [{ kind: 'string', optional: false, nullable: false }],
  'browserConsent:revoke': [{ kind: 'string', optional: false, nullable: false }],
  'calendar:addMeetingIcs': [{ kind: 'object', optional: false, nullable: false }],
  'chat:cancelStream': [{ kind: 'string', optional: false, nullable: false }],
  'chat:proactiveWelcome': [{ kind: 'string', optional: false, nullable: false }],
  'chat:send': [{ kind: 'object', optional: false, nullable: false }],
  'clusters:delete': [{ kind: 'string', optional: false, nullable: false }],
  'clusters:list': [{ kind: 'string', optional: false, nullable: false }],
  'clusters:save': [{ kind: 'object', optional: false, nullable: false }],
  'connectedApps:create': [{ kind: 'object', optional: false, nullable: false }],
  'connectedApps:delete': [{ kind: 'string', optional: false, nullable: false }],
  'connectedApps:findByHostname': [{ kind: 'string', optional: false, nullable: false }],
  'connectedApps:touch': [{ kind: 'string', optional: false, nullable: false }],
  'connectedApps:update': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }],
  'context:health': [{ kind: 'string', optional: false, nullable: false }],
  'context:markReviewed': [{ kind: 'string', optional: false, nullable: false }],
  'context:related': [{ kind: 'string', optional: false, nullable: false }],
  'context:resumeSummary': [{ kind: 'string', optional: false, nullable: false }],
  'crdt:eventsForObject': [{ kind: 'string', optional: false, nullable: false }],
  'dashboard:getLayout': [{ kind: 'string', optional: false, nullable: false }],
  'dashboard:resetLayout': [{ kind: 'string', optional: false, nullable: false }],
  'dashboard:setLayout': [{ kind: 'string', optional: false, nullable: false }, { kind: 'any', optional: false, nullable: false }],
  'decisions:cancel': [{ kind: 'string', optional: false, nullable: false }],
  'decisions:forObject': [{ kind: 'string', optional: false, nullable: false }],
  'design:export': [{ kind: 'object', optional: false, nullable: false }],
  'design:fetchImage': [{ kind: 'object', optional: false, nullable: false }],
  'design:removeBackground': [{ kind: 'object', optional: false, nullable: false }],
  'deskLayout:load': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }],
  'deskLayout:save': [{ kind: 'object', optional: false, nullable: false }],
  'docComments:list': [{ kind: 'string', optional: false, nullable: false }],
  'docComments:resolve': [{ kind: 'string', optional: false, nullable: false }, { kind: 'boolean', optional: false, nullable: false }],
  'documents:create': [{ kind: 'object', optional: false, nullable: false }],
  'documents:delete': [{ kind: 'string', optional: false, nullable: false }],
  'documents:enrich': [{ kind: 'string', optional: false, nullable: false }],
  'documents:generateSlides': [{ kind: 'object', optional: false, nullable: false }],
  'documents:get': [{ kind: 'string', optional: false, nullable: false }],
  'documents:listSnapshots': [{ kind: 'string', optional: false, nullable: false }],
  'documents:metadata': [{ kind: 'string', optional: false, nullable: false }],
  'documents:purge': [{ kind: 'string', optional: false, nullable: false }],
  'documents:restore': [{ kind: 'string', optional: false, nullable: false }],
  'documents:restoreSnapshot': [{ kind: 'string', optional: false, nullable: false }],
  'documents:update': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: false }],
  'energy:log': [{ kind: 'string', optional: false, nullable: false }],
  'energy:recent': [{ kind: 'number', optional: false, nullable: false }],
  'export:html': [{ kind: 'object', optional: false, nullable: false }],
  'export:pdf': [{ kind: 'object', optional: false, nullable: false }],
  'fileImport:parseGrid': [{ kind: 'string', optional: false, nullable: false }],
  'fileManager:addTags': [{ kind: 'string', optional: false, nullable: false }, { kind: 'any', optional: false, nullable: false }, { kind: 'any', optional: true, nullable: false }],
  'fileManager:createFolder': [{ kind: 'string', optional: false, nullable: true }, { kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: false }],
  'fileManager:createSmartFolder': [{ kind: 'string', optional: false, nullable: false }, { kind: 'any', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: false }],
  'fileManager:delete': [{ kind: 'string', optional: false, nullable: false }],
  'fileManager:deleteSmartFolder': [{ kind: 'string', optional: false, nullable: false }],
  'fileManager:entriesByTag': [{ kind: 'string', optional: false, nullable: false }],
  'fileManager:fileDocument': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: true }],
  'fileManager:get': [{ kind: 'string', optional: false, nullable: false }],
  'fileManager:importFolder': [{ kind: 'string', optional: false, nullable: true }],
  'fileManager:list': [{ kind: 'string', optional: false, nullable: true }],
  'fileManager:locateDocument': [{ kind: 'string', optional: false, nullable: false }],
  'fileManager:move': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: true }],
  'fileManager:moveToOrg': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: true }],
  'fileManager:path': [{ kind: 'string', optional: false, nullable: true }],
  'fileManager:pickFiles': [{ kind: 'string', optional: false, nullable: true }],
  'fileManager:purge': [{ kind: 'string', optional: false, nullable: false }],
  'fileManager:removeTag': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }],
  'fileManager:rename': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }],
  'fileManager:restoreDeep': [{ kind: 'string', optional: false, nullable: false }],
  'fileManager:reveal': [{ kind: 'string', optional: false, nullable: false }],
  'fileManager:search': [{ kind: 'string', optional: false, nullable: false }],
  'fileManager:tagsFor': [{ kind: 'string', optional: false, nullable: false }],
  'files:delete': [{ kind: 'string', optional: false, nullable: false }],
  'files:extractText': [{ kind: 'string', optional: false, nullable: false }],
  'files:get': [{ kind: 'string', optional: false, nullable: false }],
  'files:ingestPath': [{ kind: 'string', optional: false, nullable: false }],
  'files:ingestUrl': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: true }],
  'files:internaliseDeskImages': [{ kind: 'string', optional: false, nullable: false }],
  'files:open': [{ kind: 'string', optional: false, nullable: false }],
  'files:openExternal': [{ kind: 'string', optional: false, nullable: false }],
  'files:read': [{ kind: 'string', optional: false, nullable: false }],
  'files:suggestTags': [{ kind: 'string', optional: false, nullable: false }],
  'files:thumbnail': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: true, nullable: false }],
  'flows:create': [{ kind: 'object', optional: false, nullable: false }],
  'flows:delete': [{ kind: 'string', optional: false, nullable: false }],
  'flows:get': [{ kind: 'string', optional: false, nullable: false }],
  'flows:run': [{ kind: 'string', optional: false, nullable: false }],
  'flows:update': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }],
  'focus:complete': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }],
  'focus:recent': [{ kind: 'number', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: true }],
  'focus:start': [{ kind: 'object', optional: false, nullable: false }],
  'forms:create': [{ kind: 'object', optional: false, nullable: false }],
  'forms:delete': [{ kind: 'string', optional: false, nullable: false }],
  'forms:get': [{ kind: 'string', optional: false, nullable: false }],
  'forms:update': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }],
  'gif:search': [{ kind: 'string', optional: false, nullable: false }],
  'haptics:fire': [{ kind: 'string', optional: false, nullable: false }],
  'history:recent': [{ kind: 'number', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: true }],
  'history:record': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: true }, { kind: 'boolean', optional: true, nullable: false }],
  'knowledge:create': [{ kind: 'object', optional: false, nullable: false }],
  'knowledge:delete': [{ kind: 'string', optional: false, nullable: false }],
  'knowledge:get': [{ kind: 'string', optional: false, nullable: false }],
  'knowledge:search': [{ kind: 'string', optional: false, nullable: false }],
  'knowledge:update': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }],
  'liveDesk:get': [{ kind: 'string', optional: false, nullable: false }],
  'liveDesk:note': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: true }],
  'liveDesk:publish': [{ kind: 'string', optional: false, nullable: false }, { kind: 'any', optional: false, nullable: false }],
  'liveDesk:queuePublish': [{ kind: 'string', optional: false, nullable: false }, { kind: 'any', optional: false, nullable: false }],
  'liveDesk:setPaused': [{ kind: 'string', optional: false, nullable: false }, { kind: 'boolean', optional: false, nullable: false }],
  'liveDesk:start': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: false }],
  'liveDesk:stop': [{ kind: 'string', optional: false, nullable: false }],
  'liveDesk:uploadAsset': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'any', optional: false, nullable: false }],
  'livingPage:regenerate': [{ kind: 'string', optional: false, nullable: false }],
  'localApp:describe': [{ kind: 'string', optional: false, nullable: false }],
  'localApp:isRunning': [{ kind: 'object', optional: false, nullable: true }],
  'localApp:launch': [{ kind: 'object', optional: false, nullable: true }],
  'localApp:refreshIcon': [{ kind: 'string', optional: false, nullable: false }],
  'mail:archive': [{ kind: 'number', optional: false, nullable: false }],
  'mail:get': [{ kind: 'number', optional: false, nullable: false }],
  'mail:markSeen': [{ kind: 'number', optional: false, nullable: false }],
  'mail:saveAccount': [{ kind: 'object', optional: false, nullable: false }],
  'mail:send': [{ kind: 'object', optional: false, nullable: false }],
  'mail:suggestReply': [{ kind: 'object', optional: false, nullable: false }],
  'mail:testAccount': [{ kind: 'object', optional: false, nullable: false }],
  'marketplace:apply': [{ kind: 'string', optional: false, nullable: false }],
  'mdext:read': [{ kind: 'string', optional: false, nullable: false }],
  'mdext:write': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }],
  'meetings:audioInfo': [{ kind: 'string', optional: false, nullable: false }],
  'meetings:create': [{ kind: 'object', optional: false, nullable: false }],
  'meetings:delete': [{ kind: 'string', optional: false, nullable: false }],
  'meetings:export': [{ kind: 'string', optional: false, nullable: false }, { kind: 'any', optional: false, nullable: false }],
  'meetings:get': [{ kind: 'string', optional: false, nullable: false }],
  'meetings:getSeriesPrefs': [{ kind: 'string', optional: false, nullable: false }],
  'meetings:keepAudio': [{ kind: 'string', optional: false, nullable: false }, { kind: 'boolean', optional: false, nullable: false }],
  'meetings:loadAudioTakes': [{ kind: 'string', optional: false, nullable: false }],
  'meetings:revealAudio': [{ kind: 'string', optional: false, nullable: false }],
  'meetings:saveAudioTakes': [{ kind: 'string', optional: false, nullable: false }, { kind: 'any', optional: false, nullable: false }],
  'meetings:saveSegments': [{ kind: 'string', optional: false, nullable: false }, { kind: 'any', optional: false, nullable: false }],
  'meetings:searchSegments': [{ kind: 'string', optional: false, nullable: false }, { kind: 'number', optional: true, nullable: false }],
  'meetings:segments': [{ kind: 'string', optional: false, nullable: false }],
  'meetings:setAudioRetention': [{ kind: 'string', optional: false, nullable: false }],
  'meetings:setSeriesPrefs': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: true, nullable: false }],
  'meetings:update': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }],
  'memory:forget': [{ kind: 'string', optional: false, nullable: false }],
  'model:set': [{ kind: 'string', optional: false, nullable: false }],
  'nodes:create': [{ kind: 'object', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: false }],
  'nodes:delete': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: false }],
  'nodes:deletePermanent': [{ kind: 'string', optional: false, nullable: false }],
  'nodes:get': [{ kind: 'string', optional: false, nullable: false }],
  'nodes:listRelated': [{ kind: 'string', optional: false, nullable: false }],
  'nodes:move': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: true }, { kind: 'string', optional: false, nullable: true }],
  'nodes:moveToOrg': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: true }],
  'nodes:relate': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }],
  'nodes:restoreTree': [{ kind: 'string', optional: false, nullable: false }],
  'nodes:unrelate': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }],
  'nodes:update': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: false }],
  'notifications:post': [{ kind: 'object', optional: false, nullable: false }],
  'onboarding:record': [{ kind: 'object', optional: false, nullable: false }],
  'planner:selectItems': [{ kind: 'string', optional: false, nullable: false }, { kind: 'any', optional: false, nullable: false }],
  'projects:addDep': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: false }, { kind: 'number', optional: true, nullable: false }],
  'projects:captureBaseline': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }],
  'projects:exportXml': [{ kind: 'string', optional: false, nullable: false }],
  'projects:getCalendar': [{ kind: 'string', optional: false, nullable: false }],
  'projects:level': [{ kind: 'string', optional: false, nullable: false }],
  'projects:listBaselines': [{ kind: 'string', optional: false, nullable: false }],
  'projects:plan': [{ kind: 'string', optional: false, nullable: false }],
  'projects:removeDep': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }],
  'projects:reschedule': [{ kind: 'string', optional: false, nullable: false }],
  'projects:setCalendar': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }],
  'projects:setDep': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'number', optional: false, nullable: false }],
  'projects:setTaskPlan': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }],
  'reports:create': [{ kind: 'object', optional: false, nullable: false }],
  'reports:delete': [{ kind: 'string', optional: false, nullable: false }],
  'reports:generate': [{ kind: 'string', optional: false, nullable: false }],
  'reports:get': [{ kind: 'string', optional: false, nullable: false }],
  'reports:update': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }],
  'resume:generate': [{ kind: 'string', optional: false, nullable: false }],
  'search:query': [{ kind: 'string', optional: false, nullable: false }],
  'session:setActiveOrg': [{ kind: 'string', optional: false, nullable: false }],
  'settings:saveAnthropicKey': [{ kind: 'string', optional: false, nullable: false }],
  'settings:saveOpenAIKey': [{ kind: 'string', optional: false, nullable: false }],
  'settings:savePexelsKey': [{ kind: 'string', optional: false, nullable: false }],
  'settings:saveRemoveBgKey': [{ kind: 'string', optional: false, nullable: false }],
  'settings:saveTenorKey': [{ kind: 'string', optional: false, nullable: false }],
  'setup:buildFromPrompt': [{ kind: 'object', optional: false, nullable: true }],
  'setup:suggest': [{ kind: 'string', optional: false, nullable: false }],
  'shares:accept': [{ kind: 'object', optional: false, nullable: false }],
  'shares:delete': [{ kind: 'string', optional: false, nullable: false }],
  'shares:listForEntity': [{ kind: 'any', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }],
  'shares:removeInbox': [{ kind: 'string', optional: false, nullable: false }],
  'shares:revoke': [{ kind: 'string', optional: false, nullable: false }],
  'shares:setScope': [{ kind: 'string', optional: false, nullable: false }, { kind: 'any', optional: false, nullable: false }],
  'sheet:runMacro': [{ kind: 'object', optional: false, nullable: false }],
  'sign:create': [{ kind: 'object', optional: false, nullable: false }],
  'sign:decline': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }],
  'sign:delete': [{ kind: 'string', optional: false, nullable: false }],
  'sign:get': [{ kind: 'string', optional: false, nullable: false }],
  'sign:send': [{ kind: 'string', optional: false, nullable: false }],
  'sign:sign': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }],
  'sign:update': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }],
  'sign:void': [{ kind: 'string', optional: false, nullable: false }],
  'signals:list': [{ kind: 'number', optional: false, nullable: false }],
  'signals:markPrompted': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'number', optional: false, nullable: false }],
  'signals:matchState': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }],
  'signals:outcome': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }],
  'smartStack:propose': [{ kind: 'string', optional: false, nullable: false }],
  'snapshots:branch': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }],
  'snapshots:create': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: false }],
  'snapshots:get': [{ kind: 'string', optional: false, nullable: false }],
  'snapshots:list': [{ kind: 'string', optional: false, nullable: false }],
  'snapshots:restore': [{ kind: 'string', optional: false, nullable: false }],
  'speeddeck:saveUniversal': [{ kind: 'string', optional: false, nullable: false }],
  'tables:create': [{ kind: 'object', optional: false, nullable: false }],
  'tables:createRow': [{ kind: 'object', optional: false, nullable: false }],
  'tables:delete': [{ kind: 'string', optional: false, nullable: false }],
  'tables:deleteRow': [{ kind: 'string', optional: false, nullable: false }],
  'tables:get': [{ kind: 'string', optional: false, nullable: false }],
  'tables:listRows': [{ kind: 'string', optional: false, nullable: false }],
  'tables:reorderRows': [{ kind: 'string', optional: false, nullable: false }, { kind: 'any', optional: false, nullable: false }],
  'tables:restoreRow': [{ kind: 'string', optional: false, nullable: false }],
  'tables:update': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }],
  'tables:updateRow': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }],
  'templates:createFromTask': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: false }, { kind: 'any', optional: true, nullable: false }],
  'templates:delete': [{ kind: 'string', optional: false, nullable: false }],
  'timeblocks:create': [{ kind: 'object', optional: false, nullable: false }],
  'timeblocks:delete': [{ kind: 'string', optional: false, nullable: false }, { kind: 'any', optional: true, nullable: false }],
  'timeblocks:list': [{ kind: 'number', optional: false, nullable: false }, { kind: 'number', optional: false, nullable: false }],
  'timeblocks:update': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }],
  'trail:recent': [{ kind: 'string', optional: false, nullable: true }, { kind: 'number', optional: false, nullable: false }, { kind: 'number', optional: false, nullable: false }],
  'trail:record': [{ kind: 'object', optional: false, nullable: false }],
  'trail:summarize': [{ kind: 'string', optional: false, nullable: true }, { kind: 'number', optional: false, nullable: false }],
  'vault:changeMasterPassword': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }],
  'vault:create': [{ kind: 'string', optional: false, nullable: false }],
  'vault:createEntry': [{ kind: 'object', optional: false, nullable: false }],
  'vault:decrypt': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }],
  'vault:deleteEntry': [{ kind: 'string', optional: false, nullable: false }],
  'vault:encrypt': [{ kind: 'string', optional: false, nullable: false }],
  'vault:unlock': [{ kind: 'string', optional: false, nullable: false }],
  'vault:updateEntry': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }],
  'voice:setProvider': [{ kind: 'string', optional: false, nullable: false }],
  'widgetLinks:create': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: false }, { kind: 'string', optional: true, nullable: false }],
  'widgetLinks:delete': [{ kind: 'string', optional: false, nullable: false }],
  'widgetLinks:listByTask': [{ kind: 'string', optional: false, nullable: false }],
  'widgetLinks:update': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }],
  'widgets:bringToFront': [{ kind: 'string', optional: false, nullable: false }],
  'widgets:create': [{ kind: 'object', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: false }],
  'widgets:createOptional': [{ kind: 'object', optional: false, nullable: false }],
  'widgets:delete': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: false }],
  'widgets:get': [{ kind: 'string', optional: false, nullable: false }],
  'widgets:listByTask': [{ kind: 'string', optional: false, nullable: false }],
  'widgets:restore': [{ kind: 'string', optional: false, nullable: false }],
  'widgets:update': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: false }],
  'wireRuns:listByTask': [{ kind: 'string', optional: false, nullable: false }, { kind: 'number', optional: true, nullable: false }],
  'wireRuns:listByWire': [{ kind: 'string', optional: false, nullable: false }, { kind: 'number', optional: true, nullable: false }],
  'wires:runTransform': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: false }],
  'workItems:attestOrgMigrated': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }],
  'workItems:classify': [{ kind: 'string', optional: false, nullable: false }],
  'workItems:clearDetached': [{ kind: 'string', optional: false, nullable: false }],
  'workItems:create': [{ kind: 'object', optional: false, nullable: false }, { kind: 'object', optional: true, nullable: false }],
  'workItems:get': [{ kind: 'string', optional: false, nullable: false }],
  'workItems:kindOf': [{ kind: 'string', optional: false, nullable: false }],
  'workItems:markRead': [{ kind: 'string', optional: false, nullable: false }],
  'workItems:orgAttestation': [{ kind: 'string', optional: false, nullable: false }],
  'workItems:orgEnabled': [{ kind: 'string', optional: false, nullable: false }],
  'workItems:proposeCleanup': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: true, nullable: false }],
  'workItems:reclassify': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }],
  'workItems:revokeOrgAttestation': [{ kind: 'string', optional: false, nullable: false }],
  'workItems:scanPeople': [{ kind: 'string', optional: false, nullable: false }],
  'workItems:setEnabled': [{ kind: 'boolean', optional: false, nullable: false }],
  'workItems:setState': [{ kind: 'string', optional: false, nullable: false }, { kind: 'any', optional: false, nullable: false }, { kind: 'object', optional: true, nullable: false }],
  'workItems:snooze': [{ kind: 'string', optional: false, nullable: false }, { kind: 'number', optional: false, nullable: true }],
  'workItems:updateFields': [{ kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: false, nullable: false }, { kind: 'any', optional: false, nullable: false }, { kind: 'object', optional: true, nullable: false }],
  'workspace:adoptSharedDesk': [{ kind: 'string', optional: false, nullable: false }],
  'workspace:advanceBaseRev': [{ kind: 'string', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'number', optional: false, nullable: false }],
  'workspace:applyRemoteOrg': [{ kind: 'any', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }],
  'workspace:ask': [{ kind: 'string', optional: false, nullable: false }, { kind: 'any', optional: true, nullable: false }],
  'workspace:askStream': [{ kind: 'string', optional: false, nullable: false }, { kind: 'any', optional: false, nullable: true }, { kind: 'string', optional: false, nullable: false }, { kind: 'object', optional: true, nullable: true }],
  'workspace:fileBytesForPush': [{ kind: 'string', optional: false, nullable: false }],
  'workspace:getCursorOrg': [{ kind: 'string', optional: false, nullable: false }],
  'workspace:hasLocalFileBytes': [{ kind: 'string', optional: false, nullable: false }],
  'workspace:markPushed': [{ kind: 'any', optional: false, nullable: false }, { kind: 'string', optional: false, nullable: false }, { kind: 'number', optional: false, nullable: false }],
  'workspace:pendingOrg': [{ kind: 'string', optional: false, nullable: false }],
  'workspace:pruneSharedDesk': [{ kind: 'string', optional: false, nullable: false }],
  'workspace:related': [{ kind: 'string', optional: false, nullable: false }],
  'workspace:setCursor': [{ kind: 'number', optional: false, nullable: false }],
  'workspace:setCursorOrg': [{ kind: 'string', optional: false, nullable: false }, { kind: 'number', optional: false, nullable: false }],
  'workspace:setCursorShared': [{ kind: 'number', optional: false, nullable: false }],
  'workspace:stampSharedDesk': [{ kind: 'string', optional: false, nullable: false }],
  'workspace:writeSyncedFileBytes': [{ kind: 'string', optional: false, nullable: false }, { kind: 'any', optional: false, nullable: false }]
}
